import React, { useState } from 'react';
import MainLayout from '../layouts/MainLayout';
import AlertCard from '../components/AlertCard';
import DemoBadge from '../components/DemoBadge';
import { CLIENT_DEMO_DATA } from '../utils/demoData';
import { Bell, Filter, ShieldAlert, CheckCircle } from 'lucide-react';

const Alerts = () => {
  const [filterSeverity, setFilterSeverity] = useState('ALL');

  const alertsList = [
    {
      id: 'a1',
      type: 'High-Risk Area Alert',
      title: 'HIGH RISK AREA DETECTED',
      description: 'You are approaching Chandni Chowk market area where elevated pickpocket activity and high crowd density are reported.',
      severity: 'HIGH',
      location: 'Chandni Chowk, Delhi',
      timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
      action: 'Use the safer alternative route via Netaji Subhash Marg.'
    },
    {
      id: 'a2',
      type: 'Weather Alert',
      title: 'High Temperature & Heat Wave Warning',
      description: 'Temperature expected to cross 40°C during afternoon hours. Avoid prolonged direct sun exposure.',
      severity: 'MEDIUM',
      location: 'Jaipur, Rajasthan',
      timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
      action: 'Drink plenty of water and stay indoors from 1 PM to 4 PM.'
    },
    {
      id: 'a3',
      type: 'Traffic Alert',
      title: 'Heavy Traffic Congestion near Red Fort',
      description: 'Road closure and maintenance work on main access road causing 30-minute delays.',
      severity: 'MEDIUM',
      location: 'Red Fort Road, Delhi',
      timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
      action: 'Use Delhi Metro (Chandni Chowk Station) instead of cabs.'
    },
    {
      id: 'a4',
      type: 'Crowd Alert',
      title: 'Taj Mahal Entrance Gate Crowd Surge',
      description: 'Taj Mahal West Gate experiencing heavy ticket queue times exceeding 45 minutes.',
      severity: 'LOW',
      location: 'Taj Mahal, Agra',
      timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
      action: 'Use Taj South Gate for faster entry.'
    },
    {
      id: 'a5',
      type: 'Emergency Alert',
      title: 'Local Police Helpline Active',
      description: 'Delhi Tourist Police helpline active 24/7 at 1363 for immediate assistance.',
      severity: 'LOW',
      location: 'Delhi NCR',
      timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
      action: 'Save number 1363 in phone contacts.'
    }
  ];

  const filteredAlerts = filterSeverity === 'ALL'
    ? alertsList
    : alertsList.filter(a => a.severity === filterSeverity);

  return (
    <MainLayout title="Safety & Alert Center">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Banner */}
        <div className="glass-panel p-6 rounded-3xl border border-slate-800 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-amber-500/20 text-amber-400 border border-amber-500/30">
              <Bell className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-bold text-white">Active Safety Alerts</h2>
                <DemoBadge isLive={false} text="REAL-TIME MONITORING" />
              </div>
              <p className="text-xs text-slate-400">Proactive safety warnings generated by AI risk analysis</p>
            </div>
          </div>

          {/* Filter Buttons */}
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1 md:pb-0">
            {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => (
              <button
                key={sev}
                onClick={() => setFilterSeverity(sev)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                  filterSeverity === sev
                    ? 'bg-blue-600 text-white shadow-md shadow-blue-600/30'
                    : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>
        </div>

        {/* Alerts List */}
        <div className="space-y-4">
          {filteredAlerts.length > 0 ? (
            filteredAlerts.map((alert) => (
              <AlertCard key={alert.id} alert={alert} />
            ))
          ) : (
            <div className="p-8 text-center glass-panel rounded-3xl border border-slate-800">
              <CheckCircle className="w-10 h-10 text-emerald-400 mx-auto mb-2" />
              <h3 className="text-sm font-bold text-white">No active alerts for severity: {filterSeverity}</h3>
              <p className="text-xs text-slate-400 mt-1">All conditions are safe in this category.</p>
            </div>
          )}
        </div>
      </div>
    </MainLayout>
  );
};

export default Alerts;
